export const mockTransactions = [
  {
    source: {
      type: null,
    },
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    _id: "6390fa3cc50233ef043b61e1",
    account_owner: null,
    amount: 5.4,
    authorized_datetime: null,
    category: ["Travel", "Taxi"],
    category_id: "22016000",
    check_number: null,
    date: "2022-12-01T00:00:00.000Z",
    datetime: null,
    iso_currency_code: "USD",
    merchant_name: "Uber",
    name: "Uber 063015 SF**POOL**",
    payment_channel: "in store",
    pending: true,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_type: "special",
    unofficial_currency_code: null,
  },
  {
    source: {
      type: null,
    },
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: "3322",
    },
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    _id: "6390fa3cc50233ef043b61f3",
    account_owner: null,
    amount: 12,
    authorized_datetime: null,
    category: ["Food and Drink", "Restaurants", "Fast Food"],
    category_id: "13005032",
    check_number: null,
    date: "2022-12-06T00:00:00.000Z",
    datetime: null,
    iso_currency_code: "USD",
    merchant_name: "McDonald's",
    name: "McDonald's",
    payment_channel: "in store",
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_type: "place",
    unofficial_currency_code: null,
  },
  {
    source: {
      type: null,
    },
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    _id: "6390fa3cc50233ef043b628c",
    account_owner: null,
    amount: 4.33,
    authorized_datetime: null,
    category: ["Food and Drink", "Restaurants", "Coffee Shop"],
    category_id: "13005043",
    check_number: null,
    date: "2022-12-02T00:00:00.000Z",
    datetime: null,
    iso_currency_code: "USD",
    merchant_name: "Starbucks",
    name: "Starbucks",
    payment_channel: "in store",
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_type: "place",
    unofficial_currency_code: null,
  },
  {
    source: {
      type: null,
    },
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null,
    },
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null,
    },
    _id: "6390fa3cc50233ef043b6290",
    account_owner: null,
    amount: -500,
    authorized_datetime: null,
    category: ["Travel", "Airlines and Aviation Services"],
    category_id: "22001000",
    check_number: null,
    date: "2022-12-07T00:00:00.000Z",
    datetime: null,
    iso_currency_code: "USD",
    merchant_name: "United Airlines",
    name: "United Airlines",
    payment_channel: "in store",
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_type: "special",
    unofficial_currency_code: null,
  },
];
